### ISSUE TITLE
Rename Unlisted section

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/telegram.tools#9]
It should be called one of the below.
- Status
- Connectivity
- Health Check
- Infrastructure Information
- a combination of the above

The current name sounds like a to-do placeholder.

The description can be updated in accordance with the name change.

**Comment by roj1512** [comment]
In my opinion, your suggestions make sense only if we have more than a tool for connectivity test.

**Comment by roj1512** [comment]
In my opinion, these suggestions make sense only if we have more than a tool for connectivity test.

**Comment by KnorpelSenf** [comment]
Just add a tool that pings `api.telegram.org` if you really need to, but having a label that screams "I have no idea how to structure my site" in the most prominent position on the page does not seem like a good idea, so I feel like any name is better than the current one. Even not having a title at all would be better.

**Comment by roj1512** [comment]
CORS.

**Comment by KnorpelSenf** [comment]
```sh
$ curl -I https://api.telegram.org
HTTP/2 302 
server: nginx/1.18.0
date: Wed, 20 Mar 2024 16:54:56 GMT
content-type: text/html
content-length: 145
location: https://core.telegram.org/bots
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS
access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection
```
